# Dockerfile.backend
FROM eclipse-temurin:17-jdk-alpine AS build
WORKDIR /app
COPY backend/. .

# Dar permissão de execução para o mvnw
RUN chmod +x mvnw

# Compilar o projeto
RUN ./mvnw clean package -DskipTests

FROM eclipse-temurin:17-jdk-alpine
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]